#!/usr/bin/env bash

# Actual script directory path
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# Process ID
PID=$(ps -aux | grep -e "[m]yrssbot.py" | awk 'FNR == 1 {print $2}')

# Check if process is running
if [ ! -z "$PID" ]; then
    echo "Already running."
    exit 1
fi

# Launch the Bot
echo "Starting Script..."
source $DIR/../.venv/bin/activate
nohup python3 -u $DIR/../src/myrssbot.py >> $DIR/../output.log 2>&1 &
deactivate
sleep 1
$DIR/status

exit 0
