#!/usr/bin/env bash

# Check if process is running
PID=$(ps -aux | grep -e "[m]yrssbot.py" | awk 'FNR == 1 {print $2}')
if [ -z "$PID" ]; then
    echo "Not running."
else
    echo "Running (PID - $PID)."
fi

exit 0
